import streamlit as st
from google import genai
import os
from datetime import datetime

# =========================
# 🔐 API KEY (SAFE WAY)
# =========================
API_KEY = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=API_KEY) if API_KEY else None

# =========================
# 🎨 UI CONFIG
# =========================
st.set_page_config(
    page_title="Smart DevOps Copilot",
    page_icon="🚀",
    layout="wide"
)

st.title("🚀 Smart DevOps Copilot")
st.caption("AI-powered CI/CD error analyzer for GitLab, Docker, Kubernetes & DevOps pipelines")

# =========================
# 📁 INPUT SECTION
# =========================
uploaded_file = st.file_uploader("Upload CI/CD log file (optional)", type=["txt", "log"])
user_input = st.text_area("Enter CI/CD error or log")

pipeline_type = st.selectbox(
    "Select pipeline type",
    ["GitLab CI/CD", "Docker", "Node.js (npm)", "Kubernetes", "General DevOps"]
)

# =========================
# 🧠 LOCAL RULE ENGINE
# =========================
def local_engine(text):
    text = text.lower()
    severity = "LOW"

    if "failed" in text or "error" in text:
        severity = "HIGH"
    elif "warning" in text:
        severity = "MEDIUM"

    if "npm" in text:
        return severity, """
### 🧠 Root Cause
Node.js dependency installation failure.

### ⚙️ Fix
- delete node_modules
- run npm install
- check package.json

### 🛡️ Prevention
Use package-lock.json to lock dependencies
"""

    if "docker" in text:
        return severity, """
### 🧠 Root Cause
Docker build or missing Dockerfile issue.

### ⚙️ Fix
- verify Dockerfile exists
- docker build .
- check paths in COPY commands

### 🛡️ Prevention
Keep Dockerfile in root and use CI caching
"""

    if "gitlab" in text or "ci" in text:
        return severity, """
### 🧠 Root Cause
GitLab CI/CD pipeline misconfiguration.

### ⚙️ Fix
- validate .gitlab-ci.yml
- check indentation
- verify variables

### 🛡️ Prevention
Use GitLab CI Lint tool before pushing
"""

    return severity, None

# =========================
# 📊 REPORT BUILDER
# =========================
def build_report(input_text, result, severity):
    return f"""
# 🚀 Smart DevOps Copilot Report

**Time:** {datetime.now()}

---

## 🚨 Severity
{severity}

---

## 📌 Input
{input_text}

---

## 🔍 Analysis
{result}

---

## 🧠 Recommendation
- Fix issues step-by-step
- Re-run pipeline after correction
- Add CI caching for optimization

---
Generated by Smart DevOps Copilot
"""

# =========================
# 🚀 ANALYZE BUTTON
# =========================
if st.button("Analyze 🚀"):

    # 📁 file handling
    if uploaded_file:
        file_text = uploaded_file.read().decode(errors="ignore")
        user_input = file_text + "\n" + user_input

    # 🚫 input filter
    if not user_input or user_input.lower().strip() in ["hello", "hi", "test", ""]:
        st.warning("Please enter a valid CI/CD error or log.")
        st.stop()

    # 🧠 LOCAL ENGINE FIRST
    severity, result = local_engine(user_input)

    st.subheader(f"🚨 Severity: {severity}")

    # If local engine can solve
    if result:
        st.markdown(result)

        st.download_button(
            "⬇️ Download Report",
            build_report(user_input, result, severity),
            file_name="devops_report.txt"
        )
        st.stop()

    # =========================
    # 🤖 AI FALLBACK (Gemini)
    # =========================
    if not client:
        st.error("❌ API key not set. Set GEMINI_API_KEY environment variable.")
        st.stop()

    prompt = f"""
You are a senior DevOps engineer.

Analyze this CI/CD error:

1. Root cause
2. Step-by-step fix
3. Prevention

Pipeline Type: {pipeline_type}

Error:
{user_input}
"""

    try:
        response = client.models.generate_content(
            model="models/gemini-2.0-flash",
            contents=prompt
        )

        st.subheader("🔍 AI Analysis")
        st.markdown(response.text)

        st.download_button(
            "⬇️ Download Report",
            build_report(user_input, response.text, severity),
            file_name="devops_report.txt"
        )

    except Exception as e:
        st.error("⚠️ AI service unavailable (quota or rate limit).")

        st.info("""
### 💡 Fallback Analysis

- Check logs carefully
- Validate dependencies
- Retry pipeline after fixing issues
- Enable caching in CI/CD
""")

        st.caption(str(e))